---
- hosts: jenkins-slave 
  become: true
  tasks:
  - name: install java-11
    apt:
      name: openjdk-11-jre
      state: present
  - name: maven download packages 
    get_url:
      url: https://dlcdn.apache.org/maven/maven-3/3.9.2/binaries/apache-maven-3.9.2-bin.tar.gz
      dest: /opt
  - name: extract maven packages
    unarchive:
      src: /opt/apache-maven-3.9.2-bin.tar.gz
      dest: /opt
      remote_src: yes 
  - name: install docker 
    apt:
      name: docker
      state: present
  - name: start docker service
    service:
      name: docker 
      state: started 


   


